### ISSUE TITLE
作者您好，请问怎样修改代码让播放器能直接链接外部图片和音频呀？

### ISSUE THREAD

**Issue by sadbird520** [Meekdai/Gmemp#1]

**Comment by sadbird520** [comment]
(⊙﹏⊙)小白不懂代码，自己瞎改了现在都不能正常获取图片和音乐文件了
https://101889.xyz/player.js

**Comment by sadbird520** [comment]
因为图片和音乐文件存在不同的地方，要是能不通过文件夹这种获取方式就好了，直接能在Json文件里面填外链地址

**Comment by sadbird520** [comment]
可以一打开播放器随机播放其中的一篇么

**Comment by sadbird520** [comment]
> (⊙﹏⊙)小白不懂代码，自己瞎改了现在都不能正常获取图片和音乐文件了 https://101889.xyz/player.js

又改回来了/(ㄒoㄒ)/~~

**Comment by sadbird520** [comment]
//格式化时间为 M:SS.
  formatTime: function(secs) {
    let hour = Math.floor(secs / 3600) || 0;
    let minutes = Math.floor(secs / 60) || 0;
    let seconds = (secs - minutes * 60) || 0;
    return hour + ":" + minutes + ':' + (seconds < 10 ? '0' : '') + seconds;
  }
超过一小时就显示这样 6：360：00，不晓得咋修改

**Comment by Meekdai** [comment]
你这么多定制需求，请自行修改代码，源码很简单的，稍微学一下JS就可以修改了，使用chatGPT都可以轻松解决。

**Comment by sadbird520** [comment]
> 你这么多定制需求，请自行修改代码，源码很简单的，稍微学一下JS就可以修改了，使用chatGPT都可以轻松解决。

对不起，着急了些，好的，我自己慢慢弄，抱歉打扰了~
